/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
	'nomosenergy adapter settings': {
		'en': 'Adapter settings for nomosenergy',
		'de': 'Adaptereinstellungen für nomosenergy',
		'ru': 'Настройки адаптера для nomosenergy',
		'pt': 'Configurações do adaptador para nomosenergy',
		'nl': 'Adapterinstellingen voor nomosenergy',
		'fr': "Paramètres d'adaptateur pour nomosenergy",
		'it': "Impostazioni dell'adattatore per nomosenergy",
		'es': 'Ajustes del adaptador para nomosenergy',
		'pl': 'Ustawienia adaptera dla nomosenergy',
		'uk': 'Налаштування адаптера для nomosenergy',
		'zh-cn': 'nomosenergy的适配器设置'
	},
	'option1': {
		'en': 'option1',
		'de': 'Option1',
		'ru': 'вариант1',
		'pt': 'opção1',
		'nl': 'Option1',
		'fr': 'option1',
		'it': 'opzione1',
		'es': 'Opción1',
		'pl': 'opcja 1',
		'uk': 'Варіант1',
		'zh-cn': '选项1'
	},
	'option2': {
		'en': 'option2',
		'de': 'Option2',
		'ru': 'вариант2',
		'pt': 'opção2',
		'nl': 'Optie2',
		'fr': 'Option2',
		'it': 'opzione2',
		'es': 'opción 2',
		'pl': 'opcja2',
		'uk': 'Варіант2',
		'zh-cn': '选项2'
	}
};